/** Stable application ID prefixes. IDs are `<PREFIX>_<ULID>` and generated by the backend. */
export const ID_PREFIX = {
  project: "PRJ",
  asset: "AST",
  version: "VER",
  object: "OBJ",
  camera: "CAM",
  job: "JOB",
  generation: "GEN",
  batch: "BAT",
  material: "MAT",
} as const;

const ULID = "[0-9A-HJKMNP-TV-Z]{26}";

export function isStableId(
  id: string,
  prefix: (typeof ID_PREFIX)[keyof typeof ID_PREFIX],
): boolean {
  return new RegExp(`^${prefix}_${ULID}$`).test(id);
}
